config/routes.rb
Rails.application.routes.draw do

  resources :tags
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :posts do
    resources :comments
    resources :votes, only: [:create, :destroy]
  end

  root "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  has_many :post_tags
  has_many :tags, through: :post_tags

  belongs_to :user
  paginates_per 5
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post
    if params[:q].present?
      @posts = @posts.where(name: params[:q]).page params[:page]
    else
      @posts = @posts.page params[:page]
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @tags = Tag.all
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    byebug
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :content, tag_ids: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

  <% @tags.each do |tag| %>
    <%= tag.name %>
    <%= f.check_box :tag_ids, {multiple: true}, tag.id, [] %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
  <div class="well" id="<%= post.id%>">
    <h3><%= post.name %> </h3>

    <% post.tags.each do |tag| %>
        <%= tag.name %>
        <%= link_to "x", tag_path(tag), method: :delete %>
    <% end %>

    <p> <%= post.content %> </p>
    <p> <strong> Comentarios </strong> <%= post.comments.size %> </p>
    <p> <strong> Último Comentario </strong> <%= truncate(post.comments.try(:last).try(:content), length:6) %> </p>

    <p> <strong> Votos: </strong> <%= post.votes.size %>
    <% vote = Vote.where(user: current_user, post: post).first %>
    <% if vote.nil? %>
        <%= link_to "Up", post_votes_path(post), method: :post  %>
    <% else %>
        <%= link_to "Down", post_vote_path(post, vote), method: :delete %>
    <% end %>

    </p>

    <div class="btn-group">
    <%= link_to 'Show', post, class:'btn btn-xs btn-primary' %>
    <%= link_to 'Edit', edit_post_path(post), class:'btn btn-xs btn-warning' %>
    <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-xs btn-danger'%>
    </div>
  </div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= link_to 'New Post', new_post_path %>
<div class="row">

<div class="col-md-9">
  <%= render @posts %>
</div>

<div class="col-md-3">
  <%= paginate @posts %>

  <img src="http://vignette2.wikia.nocookie.net/pokemon/images/1/15/007Squirtle_XY_anime.png/revision/latest?cb=20140916184418" class="img-responsive">
</div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
  <hr>
	<%= link_to 'Edit', edit_post_path(@post) %> |
	<%= link_to 'Back', posts_path %>

</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<hr>

<div class="well">
	<h2> Comentarios </h2>
	<%= form_for([@post, Comment.new], class:"form") do |f| %>
		<%= f.text_area :content, class:'form-control' %>
		<%= f.submit "Enviar", class:"btn btn-primary" %>
	<% end %>
</div>

<% @post.comments.each do |c| %>
	<p> <%= link_to c.content, post_comment_path(@post, c) %>
	<%= link_to "Editar", edit_post_comment_path(@post, c) %>
	<%= link_to "Borrar", post_comment_path(@post, c), method: "Delete", class:"btn btn-danger" %>
	</p>
<% end %>